# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16inventoryservice.proto\x1a\x1bgoogle/protobuf/empty.proto\";\n\x07Product\x12\x13\n\x0bprodutct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\"\x14\n\x12ProductListRequest\"-\n\x16ProductRetrieveRequest\x12\x13\n\x0bprodutct_id\x18\x01 \x01(\x05\x32\xe4\x01\n\x10InventoryService\x12+\n\x06getAll\x12\x13.ProductListRequest\x1a\x08.Product\"\x00\x30\x01\x12)\n\x03\x61\x64\x64\x12\x08.Product\x1a\x16.google.protobuf.Empty\"\x00\x12*\n\x03get\x12\x17.ProductRetrieveRequest\x1a\x08.Product\"\x00\x12\x1e\n\x06update\x12\x08.Product\x1a\x08.Product\"\x00\x12,\n\x06\x64\x65lete\x12\x08.Product\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=55
  _PRODUCT._serialized_end=114
  _PRODUCTLISTREQUEST._serialized_start=116
  _PRODUCTLISTREQUEST._serialized_end=136
  _PRODUCTRETRIEVEREQUEST._serialized_start=138
  _PRODUCTRETRIEVEREQUEST._serialized_end=183
  _INVENTORYSERVICE._serialized_start=186
  _INVENTORYSERVICE._serialized_end=414
# @@protoc_insertion_point(module_scope)
