# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ordermanagementservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cordermanagementservice.proto\">\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x13\n\x0bprodutct_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"\x15\n\x13GetAllOrdersRequest\"8\n\x12\x43reateOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"2\n\x08Response\x12\x15\n\ris_successful\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x32\xbb\x01\n\x16OrderManagementService\x12*\n\x06getAll\x12\x14.GetAllOrdersRequest\x1a\x06.Order\"\x00\x30\x01\x12\'\n\x06\x63reate\x12\x13.CreateOrderRequest\x1a\x06.Order\"\x00\x12$\n\x06\x63\x61ncel\x12\r.OrderRequest\x1a\t.Response\"\x00\x12&\n\x08\x63omplete\x12\r.OrderRequest\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ordermanagementservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER._serialized_start=32
  _ORDER._serialized_end=94
  _GETALLORDERSREQUEST._serialized_start=96
  _GETALLORDERSREQUEST._serialized_end=117
  _CREATEORDERREQUEST._serialized_start=119
  _CREATEORDERREQUEST._serialized_end=175
  _RESPONSE._serialized_start=177
  _RESPONSE._serialized_end=227
  _ORDERREQUEST._serialized_start=229
  _ORDERREQUEST._serialized_end=261
  _ORDERMANAGEMENTSERVICE._serialized_start=264
  _ORDERMANAGEMENTSERVICE._serialized_end=451
# @@protoc_insertion_point(module_scope)
