# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ordermanagementservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cordermanagementservice.proto\x1a\x1bgoogle/protobuf/empty.proto\">\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x13\n\x0bprodutct_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"(\n\x14OrderRetrieveRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x32\xb1\x01\n\x16OrderManagementService\x12\'\n\x03\x61\x64\x64\x12\x06.Order\x1a\x16.google.protobuf.Empty\"\x00\x12&\n\x03get\x12\x15.OrderRetrieveRequest\x1a\x06.Order\"\x00\x12\x1a\n\x06update\x12\x06.Order\x1a\x06.Order\"\x00\x12*\n\x06\x64\x65lete\x12\x06.Order\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ordermanagementservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER._serialized_start=61
  _ORDER._serialized_end=123
  _ORDERRETRIEVEREQUEST._serialized_start=125
  _ORDERRETRIEVEREQUEST._serialized_end=165
  _ORDERMANAGEMENTSERVICE._serialized_start=168
  _ORDERMANAGEMENTSERVICE._serialized_end=345
# @@protoc_insertion_point(module_scope)
